import React from 'react';
import { 
  Activity, 
  FileText, 
  Flag, 
  Globe, 
  AlertCircle, 
  CheckCircle, 
  Clock, 
  UploadCloud, 
  Search,
  ShieldAlert,
  FileCode,
  Terminal,
  Copy,
  ClipboardCheck,
  ListChecks,
  Lightbulb,
  Key,
  BookOpen,
  Users,
  Home,
  Wrench,
  ArrowRight,
  X
} from 'lucide-react';

export const Icons = {
  Overview: Activity,
  Logs: Terminal,
  Api: Globe,
  Flags: Flag,
  Files: FileText,
  Success: CheckCircle,
  Error: AlertCircle,
  Time: Clock,
  Upload: UploadCloud,
  Scan: Search,
  Search: Search,
  Results: ShieldAlert,
  Code: FileCode,
  Copy: Copy,
  Precheck: ClipboardCheck,
  Summary: ListChecks,
  Suggestion: Lightbulb,
  Key: Key,
  Knowledge: BookOpen,
  Users: Users,
  Home: Home,
  Tool: Wrench,
  ArrowRight: ArrowRight,
  Close: X
};